package com.microservices.demo.elastic.indexclient.repository;

import com.microservices.demo.elastic.model.index.TwitterIndexModel;
import org.springframework.data.elasticsearch.repository.ElasticsearchRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface TwitterElasticsearchIndexRepository extends ElasticsearchRepository<TwitterIndexModel, String> {
    //methods are generated by spring
}
