server:
  port: 8888

#overrides settings in logback.xml
logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wondercrunch/spring-cloud-config-server-repo
          default-label: main
          username: wondercrunch
          password: token
          clone-on-start: true #clone config repo on startup
    fail-fast: true #if config server cannot reach config server repo it will stop immediately
  security:
    user:
      name: spring_cloud_user
      password: springCloudPwd!